# Generated by Django 3.1.3 on 2021-03-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pregenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregenre1', models.CharField(max_length=45)),
                ('pregenre2', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'pregenre',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('artist', models.CharField(max_length=45)),
                ('album', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=45)),
                ('dates', models.DateField()),
                ('lyrics', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'song',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=45)),
                ('song', models.ManyToManyField(to='page.Song')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
    ]
