# Generated by Django 3.1.3 on 2021-04-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('artist', models.CharField(max_length=45)),
                ('album', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=45)),
                ('dates', models.DateField()),
                ('lyrics', models.CharField(max_length=2000)),
                ('tag', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'song',
            },
        ),
    ]
